### PR TITLE
Add optional -d argument to output dotfile.

### PR DESCRIPTION
**Pull request by daroot**
In case you want to fine tune the output before passing it to graphviz.

### CODE REVIEW

**Comment by Alexis-benoist** [comment]
It would be perfect if you encapsulated the Io in a function.
Just as a curiosity, how do you customise the output?

**Comment by daroot** [comment]
Just made the change suggested.

Mostly I was looking to change the layout by using some subgraph ranking.   Pin the data stores to max rank, while pinning the containers that interact directly with the outside world to the min rank.   The document was for some internal team system diagrams, so I also ended up fiddling with some of the edge weights to force various containers closer to logically similar containers.

**Comment by Alexis-benoist** [comment]
Cool!
Do you mind sharing with me the graphviz code you used?

**Comment by daroot** [comment]
Here you go, safely anonymized.  

The additions are just a couple of ranks and a couple of weights to make sure that appropriate clusters end up together. 

```
digraph {
    graph [rankdir=LR];
    node [label="\N",
        shape=box,
        style=filled,
        color=".7 .3 1.0"
    ];
    edge [color=gray50,
    arrowhead=normal,
    minlen=2
    ];
"a2";
"v5";
"v3";
"v4";
"web3";
"dl1";
"ac2";
"ac3";
"web1";
"v2";
"db1";
"apip";
"api2";
"api1";
"v1";
"ac1";
"db2";
"nd1";
"web2";
"a3";
"db4";
"n1";
"a1";
"a2" -> "a1"
"a2" -> "ac3"
"a2" -> "n2"
"v5" -> "v1"
"v5" -> "db1"
"v5" -> "ac1"
"v5" -> "v3" [weight=50];
"v3" -> "db1"
"v3" -> "ac1"
"v3" -> "ac2"
"v3" -> "v6"
"v4" -> "db1"
"v4" -> "ac1"
"v4" -> "v1" [weight=100];
"web3" -> "db1"
"web3" -> "db3"
"web3" -> "ac2"
"web3" -> "q1"
"dl1" -> "db4"
"dl1" -> "wd1"
"ac1" -> "ac2"
"ac2" -> "db1"
"ac2" -> "db2"
"ac2" -> "db3"
"ac2" -> "wd1"
"ac3" -> "nd1"
"ac3" -> "n1"
"ac3" -> "a3"
"ac3" -> "db1"
"ac3" -> "db5"
"ac3" -> "f1"
"web1" -> "api1"
"web1" -> "db1"
"web1" -> "ac2"
"web1" -> "db3"
"web1" -> "q1"
"v2" -> "v4" [weight=100];
"v2" -> "db1"
"v2" -> "ac2"
"api2" -> "db1"
"api2" -> "a2"
"api2" -> "ac3"
"api1" -> "db1"
"api1" -> "db3"
"apip" -> "api1" [weight=75];
"apip" -> "api2" [weight=75];
"v1" -> "v4" [weight=100];
"v1" -> "ac1"
"v1" -> "db1"
"ac1" -> "db1"
"ac1" -> "db4"
"ac1" -> "db3"
"ac1" -> "n1"
"web2" -> "db1"
"web2" -> "q1"
"web2" -> "db3"
"n2" -> "nd1" [weight=75];
"n1" -> "nd1" [weight=75];
"a1" -> "a2"

{ rank=min; a1; v1; v2; v3; dl1; web1; }
{ rank=same; db2; db3; db4; }
{ rank=max; db1; db5; }
}
```

**Pull request merged**
